services:
  coredns:
    image: coredns/coredns:1.11.1
    container_name: coredns
    restart: unless-stopped
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./dns/Corefile:/etc/coredns/Corefile:ro
      - ./dns/zones:/zones:ro
    command: ["-conf", "/etc/coredns/Corefile"]
    networks:
      - npm-network

networks:
  npm-network:
    external: true
