services:
  velocity-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: velocity-prod
    restart: unless-stopped
    networks:
      - npm-network

networks:
  npm-network:
    external: true
