http:
  middlewares:
    redirect-https:
      redirectScheme:
        scheme: https
        permanent: true

  routers:
    redirect:
      rule: "HostRegexp(`{host:.+}`)"
      entryPoints: [web]
      service: noop@internal
      middlewares: [redirect-https]
