name: Deploy Prod Frontend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: prod-frontend
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Build image
        working-directory: prod-frontend
        run: docker compose build

      - name: Deploy
        working-directory: prod-frontend
        run: docker compose up -d --remove-orphans
