name: Deploy Prod Frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'prod-frontend/**'
  workflow_dispatch:

concurrency:
  group: prod-frontend
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: false

      # (опционально) собрать .env из секретов для Vite:
      # env:
      #   VITE_SUPABASE_URL: ${{ secrets.PROD_SUPABASE_URL }}
      #   VITE_SUPABASE_ANON_KEY: ${{ secrets.PROD_SUPABASE_ANON_KEY }}
      # - name: Write .env
      #   working-directory: prod-frontend
      #   run: |
      #     cat > .env <<EOF
      #     VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      #     VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      #     EOF

      - name: Build image
        working-directory: prod-frontend
        run: docker build -t velocity-prod .

      - name: Stop old
        run: docker stop velocity-prod || true && docker rm velocity-prod || true

      - name: Run new
        run: |
          docker run -d \
            --name velocity-prod \
            --restart unless-stopped \
            --network npm-network \
            velocity-prod

      - name: Status
        run: docker ps --filter name=velocity-prod
