name: Self-Hosted Runner Job
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, linux, x64, docker]  # метки должны точно совпадать с твоими
    steps:
      - name: Show Runner Hostname
        run:  echo "Running on runner: $HOSTNAME"
      - name: Run Hello World
        run: docker run --rm hello-world
